export const TIMER_CONSTANTS = {
	ITEM_HEIGHT: 50,
	VISIBLE_ITEMS: 3,
	CONTAINER_HEIGHT: 150, // ITEM_HEIGHT * VISIBLE_ITEMS
};

export const COLORS = {
	PRIMARY: '#1E2A3A',
	SECONDARY: '#94A3B8',
	TEXT_DARK: '#0E1621',
	TEXT_LIGHT: '#64748B',
	ACCENT_RED: '#EF4444',
	ACCENT_GREEN: '#BFE7D4',
	BACKGROUND_LIGHT: '#F1F5F9',
	WHITE: '#FFFFFF',
};
